version: '3.5'

services:
  api:
    build: ./todo-api
    networks:
      - app-network

  nginx:
    image: 'nginx:1.18.0-alpine'
    volumes:
      - './nginx/conf.d/:/etc/nginx/conf.d/'
    ports:
      - '8080:80'
    networks:
      - app-network

  webapp:
    image: nginx
    volumes:
      - ./webapp/public:/usr/share/nginx/html:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge